joint_limits:
  right_wheel_joint:
    has_velocity_limits: true
    max_velocity: 15.0
    has_effort_limits: true
    max_effort: 78e-3
  left_wheel_joint:
    has_velocity_limits: true
    max_velocity: 15.0
    has_effort_limits: true
    max_effort: 78e-3
