joint_limits:
  right_wheel_joint:
    has_velocity_limits: true
    max_velocity: 30.0
    has_effort_limits: true
    max_effort: 70.0e-3
  left_wheel_joint:
    has_velocity_limits: true
    max_velocity: 30.0
    has_effort_limits: true
    max_effort: 70.0e-3
